apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: image-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-catalog
  template:
    metadata:
      labels:
        app: image-catalog
    spec:
      containers:
        - image: baraba123/rso-image-catalog:1.0.0-SNAPSHOT-24.1
          name: image-catalog
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: rso
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://52.188.78.101:8080
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ec2-174-129-255-10.compute-1.amazonaws.com:5432/dda01e82h4eo6u
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: rrusmqcilifpun
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: fced1fb5d5b33879d657e5629f206ec638c171a2270013d233ad6a43985a56ba
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: image-catalog
spec:
  type: ClusterIP
  selector:
    app: image-catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: server
